spring:
  resources:
    static-locations: classpath:/static/
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    enabled: true
  profiles:
    active:
    - redis
    - single-datasource
server:
  port: 8080
logging:
  level:
    ${package}.${artifactId}: info