spring:
  fastjson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  freemarker:
    cache: false
  profiles:
    active:
    - redis
    - single-datasource
server:
  port: 8080
logging:
  level:
    ${package}.${artifactId}: info