#多数据源列表，与单数据源二选一。如果既设置了单数据源，又设置了多数据源，则以多数据源为准
#如果要启用,则在application.yml中spring.profiles.active添加一个multiple-datasource列表对象
datasource:
  #存放Config.java的配置文件的包
  config-package: com.h3w.config
  datasource-properties-list:
  - name: mysql
    primary: true
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type-aliases-package: com.h3w.entity
    mapper-package: com.h3w.mapper
    mapper-locations: classpath:/mapper
  - name: test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type-aliases-package: com.h3w.entity
    mapper-package: com.h3w.mapper
    mapper-locations: classpath:mapper
